// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import SearchController from "./search_controller.js"
application.register("search", SearchController)

import SearchResultsController from "./search_results_controller.js"
application.register("search-results", SearchResultsController)
